#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
    path: /logout

api_login_check:
    path: /api/login_check

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin